In [314]:
import nltk

In [315]:
import nltk.tokenize.punkt
# Utgår tills vidare från https://machinelearningmastery.com/clean-text-machine-learning-python/ 
# Det som saknas i nltk laddas ner via konstigt GUI direkt i Python3: >>> import nltk >>> nltk.download()

In [316]:
# load data
filename = 'sou_1944.txt'
file = open(filename, 'rt')
text = file.read()
file.close()

In [317]:
avspaerra = re.compile('(?<=\s\S)\s(?!\S\S)', re.S)
text = re.sub(avspaerra, '', text)
text = text.replace('\n',' ')

In [318]:
# split into sentences
from nltk import sent_tokenize
sentences = sent_tokenize(text)
print(sentences[0])

National Library of Sweden  Denna bok digitaliserades på Kungl.


In [319]:
len(sentences)

5459

In [320]:
# split into words
from nltk.tokenize import word_tokenize
tokens = word_tokenize(text)
print(tokens[900:1000])

['III', '.', 'Kap', '.', 'IV', '.', 'Kap', '.', 'V.', '70', 'Allmänna', 'barnhusets', 'verksamhet', '72', 'Barnhemmens', 'ekonomiska', 'förhållanden', '79', 'Vissa', 'brister', 'hos', 'den', 'slutna', 'barnavården', '85', 'Olika', 'kategorier', 'barnavårdsanstalter', 'enligt', 'kommitténs', 'förslag', 'Vissa', 'lagtekniska', 'spörsmål', 's.', '90', '.', 'Om', 'begreppet', 'barnavårds', 'ans', 'tält', 's.', '90.', 'olika', 'kategorierna', 'barnavårds', 'anstalter', 'enligt', 'kommitténs', 'förslag', 's.', '94', '.', 'Kap', '.', '90', 'De', 'VI', 'Allmänna', 'riktlinjer', 'för', 'barnhemmens', 'verksamhet', 'Allmänna', 'synpunkter', 's.', '96', '.', 'Hem', 'för', 'mödrar', 'och', 'späda', 'barn', '96', '97', 'Gemensamma', 'synpunkter', 's.', '97', '.', 'Mödrahemmen', 's.', '104', '.', 'Hemskolor', 'för', 'mödrar', 's.', '111', '.', 'Vårdhem', 'för', 'mödrar', 's.', '115..', 'Vården', ',', 'av']


In [321]:
len(tokens)

134686

In [322]:
# remove all tokens that are not alphabetic
words = [word for word in tokens if word.isalpha()]
print(words[:1000])

['National', 'Library', 'of', 'Sweden', 'Denna', 'bok', 'digitaliserades', 'på', 'Kungl', 'biblioteket', 'år', 'SOCIALDEPARTEMENTET', 'SOCIALVÅRDSKOMMITTÉNS', 'BETÄNKANDE', 'IX', 'UTREDNING', 'OCH', 'FÖRSLAG', 'ANGÅENDE', 'REVISION', 'AV', 'LAGSTIFTNINGEN', 'OM', 'BARNAVÅRDSANSTALTER', 'OCH', 'FOSTERBARNSVÅRD', 'STOCKHOLM', 'Statens', 'offentliga', 'utredningar', 'jf', 'örteckni', 'g', 'Jordbruksbefolkningenslevnadskostnader', 'Av', 'Jo', 'Betänkandemed', 'förslag', 'angåendelångtjänstunderbefälm', 'Beckman', 'Fö', 'Betänkandeangåendenykterhetstillståndetunder', 'krigså', 'Fi', 'Promemoriamod', 'förslag', 'tilllagmedbestämmelser', 'om', 'allmänna', 'behörighetsvillkor', 'för', 'vissa', 'Hseggström', 'Betänkandemed', 'förslag', 'till', 'Betänkandemed', 'förslag', 'till', 'byordningarochinstruktioner', 'för', 'Jo', 'Utredningarangåendeekonomiskefterkrigsplanering', 'Marcus', 'Fi', 'Betänkandemed', 'förslag', 'Ju', 'Processlagbereduingens', 'förslag', 'till', 'lagominförande', 'av', 'Ju',

In [323]:
from nltk.corpus import stopwords
stop_words = stopwords.words('swedish')
print(stop_words)

['och', 'det', 'att', 'i', 'en', 'jag', 'hon', 'som', 'han', 'på', 'den', 'med', 'var', 'sig', 'för', 'så', 'till', 'är', 'men', 'ett', 'om', 'hade', 'de', 'av', 'icke', 'mig', 'du', 'henne', 'då', 'sin', 'nu', 'har', 'inte', 'hans', 'honom', 'skulle', 'hennes', 'där', 'min', 'man', 'ej', 'vid', 'kunde', 'något', 'från', 'ut', 'när', 'efter', 'upp', 'vi', 'dem', 'vara', 'vad', 'över', 'än', 'dig', 'kan', 'sina', 'här', 'ha', 'mot', 'alla', 'under', 'någon', 'eller', 'allt', 'mycket', 'sedan', 'ju', 'denna', 'själv', 'detta', 'åt', 'utan', 'varit', 'hur', 'ingen', 'mitt', 'ni', 'bli', 'blev', 'oss', 'din', 'dessa', 'några', 'deras', 'blir', 'mina', 'samma', 'vilken', 'er', 'sådan', 'vår', 'blivit', 'dess', 'inom', 'mellan', 'sådant', 'varför', 'varje', 'vilka', 'ditt', 'vem', 'vilket', 'sitta', 'sådana', 'vart', 'dina', 'vars', 'vårt', 'våra', 'ert', 'era', 'vilkas']


In [324]:
# convert to lower case
tokens = [w.lower() for w in tokens]
# remove punctuation from each word
import string
table = str.maketrans('', '', string.punctuation)
stripped = [w.translate(table) for w in tokens]
# remove remaining tokens that are not alphabetic
words = [word for word in stripped if word.isalpha()]
# filter out stop words
from nltk.corpus import stopwords
stop_words = set(stopwords.words('swedish'))
words = [w for w in words if not w in stop_words]
print(words[:100])

['national', 'library', 'of', 'sweden', 'bok', 'digitaliserades', 'kungl', 'biblioteket', 'år', 'j', 'socialdepartementet', 'socialvårdskommitténs', 'betänkande', 'ix', 'utredning', 'förslag', 'angående', 'revision', 'lagstiftningen', 'barnavårdsanstalter', 'fosterbarnsvård', 'stockholm', 'statens', 'offentliga', 'utredningar', 'jf', 'örteckni', 'g', 'jordbruksbefolkningenslevnadskostnader', 'elindahlochllemnemarcus', 's', 'jo', 'betänkandemed', 'förslag', 'angåendelångtjänstunderbefälm', 'm', 'beckman', 's', 'fö', 'betänkandeangåendenykterhetstillståndetunder', 'krigså', 'renmarcus', 's', 'fi', 'promemoriamod', 'förslag', 'tilllagmedbestämmelser', 'allmänna', 'behörighetsvillkor', 'vissa', 'kommunalauppdragmm', 'hseggström', 's', 's', 'betänkandemed', 'förslag', 'civilförsvarslagnimbeckman', 's', 's', 'betänkandemed', 'förslag', 'byordningarochinstruktioner', 'ordningsmannenilappbyarnamarcus', 's', 'jo', 'utredningarangåendeekonomiskefterkrigsplanering', 'marcus', 's', 'fi', 'betänkan

In [325]:
"""
# load data
filename = 'sou_1944.txt'
file = open(filename, 'rt')
text = file.read()
file.close()
# split into words
from nltk.tokenize import word_tokenize
tokens = word_tokenize(text)
# stemming of words
from nltk.stem.porter import PorterStemmer
porter = PorterStemmer()
stemmed = [porter.stem(word) for word in tokens]
print(stemmed[:100])
"""

"\n# load data\nfilename = 'sou_1944.txt'\nfile = open(filename, 'rt')\ntext = file.read()\nfile.close()\n# split into words\nfrom nltk.tokenize import word_tokenize\ntokens = word_tokenize(text)\n# stemming of words\nfrom nltk.stem.porter import PorterStemmer\nporter = PorterStemmer()\nstemmed = [porter.stem(word) for word in tokens]\nprint(stemmed[:100])\n"

In [326]:
from afinn import Afinn

In [327]:
# Fixade i afinn.py och laddade ner AFINN-sv-165.txt
afinn = Afinn(language='sv')

In [328]:
afinn.score(sentences[0])

0.0

In [329]:
import numpy as np

In [330]:
scores = np.empty(len(sentences))

In [331]:
scores

array([ -1.28822975e-231,  -1.28822975e-231,   2.39597414e-314, ...,
         2.43036979e-314,   2.43037096e-314,   2.43037816e-314])

In [332]:
for index, sentence in enumerate(sentences):
    scores[index] = afinn.score(sentence)

In [333]:
scores

array([ 0.,  0.,  0., ...,  0.,  0.,  0.])

In [334]:
np.max(scores)

16.0

In [335]:
np.where(scores==16.0)

(array([4426]),)

In [336]:
scores[4426]

16.0

In [337]:
sentences[4426]

'Ett anmärkningsvärt stort antal nämnder (22) ha emellertid uttalat, att någon skillnad i detta hänseende icke bor upprätthållas mellan fosterhem, som mottaga barnbarn, och övriga fosterhem Flera nämnder understryka, att fosterföräldrar, som uppnått en hog ålder icke bli lämpligare, därför att de äro släkt med barnet, och yttranden sådana som dessa förkomma: »Enligt nämndens mening aro mor- och farföräldrar i regel mindre lämpliga som fosterföräldrar (Örebro); »Att dessa hem hos gamla anhöriga skulle vara på något sätt bättre än fosterhem hos andra oskylda åldringar kan nämnden emellertid ej hålla med om» (Arvika); »Då far- och morföräldrarna ge nämnden de avgjort mesta besvärligheterna, bör för denna kategori stadgas, att de skola anses lämpliga, endast om de äro relativt unga och arbetsföra» (Fagerhult); samt »De fosterbarn, som ha de sämsta hemmen, vårdas ofta av gamla far- och morföräldrar» (Domnarvet).'

In [338]:
np.min(scores)

-11.0

In [339]:
index = np.where(scores==np.min(scores))

In [340]:
index[0][0]

4791

In [341]:
sentences[np.where(scores==np.min(scores))[0][0]]

'a. på talan av barnavårdsnämnd — förordna, att vårdnaden skall tillkomma allenast den ene av föräldrarna, därest den andre gör sig skyldig till grovt missbruk eller till grov försummelse vid vårdnadens utövande, eller om han är hemfallen åt missbruk av rusgivande medel eller för ett lastbart liv, eller om han till följd av frånvaro, sjukdom eller annan orsak är för längre tid förhindrad deltaga i vårdnaden.'

In [343]:
text2 = nltk.Text(word.lower() for word in text)

In [344]:
text2.concordance("andre")

No matches


In [345]:
text2

<Text: n a t i o n a l...>

In [346]:
len(text2)

831819

In [347]:
text2.similar('sig')

No matches


In [348]:
text2 = word_tokenize(text)

In [349]:
tagged = nltk.pos_tag(text)

In [350]:
tagged = np.array(tagged)

In [351]:
words = tagged[:,0]

In [352]:
words

array(['N', 'a', 't', ..., ' ', ' ', '\x0c'],
      dtype='<U4')

In [353]:
for word in tagged:
    word[2] = len(word[0])

IndexError: index 2 is out of bounds for axis 0 with size 2

In [354]:
emp = np.empty(len(tagged))

In [355]:
emp

array([ 0.,  0.,  0., ...,  0.,  0.,  0.])

In [356]:
np.array(emp).shape

(831819,)

In [357]:
np.hstack((tagged, [emp]))

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [358]:
nl_text = nltk.Text(tokens)

In [359]:
nl_text.collocations()

enligt kommitténs; kommitténs mening; stadigvarande vård; kommitténs
förslag; hänsyn till; späda barn; med hänsyn; samband med; och
uppfostran; hög grad; allmänna barnhuset; för närvarande; kommittén
har; halvöppen barnavård; framför allt; detta sammanhang; varaktig
vård; sakens natur; den mån; vård och


In [360]:
nl_text

<Text: national library of sweden denna bok digitaliserades på...>

In [361]:
len(nl_text)

134686

In [363]:
nl_text[2500:4000]

['i',
 'kommunallagarna',
 '!',
 '2',
 'mom',
 '.',
 'barnavårdsnämnden',
 'bör',
 'utvecklingen',
 'av',
 'barnavårdsanstalter',
 'och',
 'ungdoms',
 'välfärd',
 '.',
 'barnavårdsnämnden',
 'åligger',
 'formerna',
 'därför',
 '.',
 'h',
 '§',
 '.',
 '1',
 'mom',
 '.',
 'barnavårdsnämnden',
 'bör',
 'av',
 'arbetet',
 '.',
 '2',
 'mom',
 '.',
 'jämväl',
 'för',
 '—',
 'eller',
 'stiftelse',
 '.',
 'barnavårdsnämnden',
 'må',
 'barnavårdsnämndens',
 'angelägenhet',
 '.',
 'där',
 'ej',
 'särskilda',
 'omständigheter',
 'annat',
 'föranleda',
 ',',
 'skall',
 'nämnden',
 'utse',
 'en',
 'eller',
 'flera',
 'ledamöter',
 'eller',
 'suppleanter',
 'i',
 'nämnden',
 '(',
 'anstaltsdelegerade',
 ')',
 'att',
 'ägna',
 'särskild',
 'uppmärksamhet',
 'åt',
 'de',
 'inom',
 'kommunen',
 'belägna',
 'barnavårdsanstalternas',
 'verksamhet',
 '.',
 '17',
 '§',
 '.',
 'vill',
 'någon',
 'eller',
 'ordföranden',
 '.',
 'kommunal',
 'myndighet',
 ',',
 'befattningshavare',
 'i',
 'statens',
 ',',
 'l